spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8080

swagger:
  server-url: https://dev-api.saerok.app

aws:
  credentials:
    access-key: ${IAM_ACCESS_KEY}
    secret-key: ${IAM_SECRET_KEY}
  region: ap-northeast-2
  s3:
    bucket: ${BUCKET_NAME}
  cloudfront:
    image-domain: ${CLOUDFRONT_IMAGE_DOMAIN}