spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    locations: classpath:db/migration

server:
  port: 8080

swagger:
  server-url: https://dev-api.saerok.app

aws:
  credentials:
    access-key: ${IAM_ACCESS_KEY}
    secret-key: ${IAM_SECRET_KEY}
  region: ap-northeast-2
  s3:
    bucket: ${BUCKET_NAME}
  cloudfront:
    image-domain: ${CLOUDFRONT_IMAGE_DOMAIN}

apple:
  client-id: ${APPLE_CLIENT_ID}
  team-id: ${APPLE_TEAM_ID}
  key-id: ${APPLE_KEY_ID}
  private-key: ${APPLE_PRIVATE_KEY}

kakao:
  client-id: ${DEV_KAKAO_CLIENT_ID}
  redirect-uri: ${DEV_KAKAO_REDIRECT_URI}
  client-secret: ${DEV_KAKAO_CLIENT_SECRET}

app:
  cookie:
    secure: true