spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    locations: classpath:db/migration

server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      directory: /home/ubuntu/saerok/accesslogs
      prefix: access_log
      suffix: .log
      rotate: true
      pattern: '%h %t "%m %U%q" %s %b %D'

logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql.BasicBinder: off

swagger:
  server-url: https://dev-api.saerok.app

aws:
  credentials:
    access-key: ${IAM_ACCESS_KEY}
    secret-key: ${IAM_SECRET_KEY}
  region: ap-northeast-2
  s3:
    upload-image-bucket: ${UPLOAD_IMAGE_BUCKET_NAME}
    dex-image-bucket: ${DEX_IMAGE_BUCKET_NAME}
  cloudfront:
    upload-image-domain: ${UPLOAD_IMAGE_DOMAIN}
    dex-image-domain: ${DEX_IMAGE_DOMAIN}
  kms:
    key-id: ${KMS_KEY_ID}

apple:
  client-id: ${APPLE_CLIENT_ID}
  team-id: ${APPLE_TEAM_ID}
  key-id: ${APPLE_KEY_ID}
  private-key: ${APPLE_PRIVATE_KEY}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  client-secret: ${KAKAO_CLIENT_SECRET}
  admin-key: ${KAKAO_ADMIN_KEY}

app:
  cookie:
    secure: true

cors:
  allowed-origins:
    - http://localhost:3000